### ISSUE TITLE
Slow Training- Need entire model 

### ISSUE THREAD

**Issue by Primadual** [bubbliiiing/facenet-tf2#2]
Hi. Thanks for the code and efforts. My training is slow. It takes about 4 hours per epoch. Do you by any chances have the "entire model" saved somewhere that you can share with me? This is the code I use to save the whole model so I can load it in Java later on (Checkpoints alone won't work):

            # Save the weights using the `checkpoint_path` format
            # Include the epoch in the file name (uses `str.format`)
            checkpoint_path = "checkpoints/cp-{epoch:04d}.ckpt"
            checkpoint_dir = os.path.dirname(checkpoint_path)
            shutil.rmtree(checkpoint_dir)
            model.save_weights(checkpoint_path.format(epoch=0))

            # Save the entire model
            modelSavePath = 'saved_model'
            shutil.rmtree(modelSavePath)
            model.save('saved_model/FaceVerify')

**Comment by Primadual** [comment]
So I also can't load the saved model when I try to predict!! I think because we have freez and unfreez they backbone models don't get saved with the model. Do you know a way to save the entire model with the backbone models (MobileNet, Facenet) altogether? Here is the code I use to load the model:

import tensorflow as tf
from PIL import Image
from tensorflow import keras
import numpy as np
from facenet import Facenet

gpus = tf.config.experimental.list_physical_devices(device_type='GPU')
for gpu in gpus:
    tf.config.experimental.set_memory_growth(gpu, True)
    
model = tf.keras.models.load_model('saved_model/FaceVerify')

And here is the error I get:

File "predict_MyModel.py", line 21, in <module>
    model = tf.keras.models.load_model('saved_model/FaceVerify')
  File "C:\Users\ll\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\keras\saving\save.py", line 187, in load_model
    return saved_model_load.load(filepath, compile, options)
  File "C:\Users\ll\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\keras\saving\saved_model\load.py", line 131, in load
    training_config))
  File "C:\Users\ll\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\keras\saving\saving_utils.py", line 217, in compile_args_from_training_config
    loss = _deserialize_nested_config(losses.deserialize, loss_config)
  File "C:\Users\ll\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\keras\saving\saving_utils.py", line 262, in _deserialize_nested_config
    for k, v in config.items()
  File "C:\Users\ll\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\keras\saving\saving_utils.py", line 262, in <dictcomp>
    for k, v in config.items()
  File "C:\Users\ll\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\keras\saving\saving_utils.py", line 258, in _deserialize_nested_config
    return deserialize_fn(config)
  File "C:\Users\ll\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\keras\losses.py", line 1854, in deserialize
    printable_module_name='loss function')
  File "C:\Users\ll\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py", line 378, in deserialize_keras_object
    'Unknown ' + printable_module_name + ': ' + object_name)
ValueError: Unknown loss function: _triplet_loss

**Comment by bubbliiiing** [comment]
1. The slow training speed may be due to the comparison of data loading, rather than network reasons. You can try to turn off data enhancement and use a better solid state drive. When not using eager mode, you can set num_works.
2. I suggest that you don't need to save during training, you can save during prediction, just add the code in the facenet.py file. It should have nothing to do with freezing and non-freezing.

**Comment by Primadual** [comment]
Thanks for your reply. I did as you suggested. Left the train.py code untouched and instead added the save entire model code to the facenet.py. Now it does not save anything at all!
Are you sure that is the right place to save the model? 
I need the fully trained model entirely saved after training. So when I predict, I load the entire model, take an image, read it and make prediction. My deployment environment is in JAVA, so all prediction has to happen in JAVA. That's why I need to save the ENTIRE model.
Here is my modified facenet.py code:

import os
import matplotlib.pyplot as plt
import numpy as np
from PIL import Image
from nets.facenet import facenet


#--------------------------------------------#
#   使用自己训练好的模型预测需要修改2个参数
#   model_path和backbone需要修改！
#--------------------------------------------#
class Facenet(object):
    _defaults = {
        #--------------------------------------------------------------------------#
        #   使用自己训练好的模型进行预测要修改model_path，指向logs文件夹下的权值文件
        #   训练好后logs文件夹下存在多个权值文件，选择验证集损失较低的即可。
        #   验证集损失较低不代表准确度较高，仅代表该权值在验证集上泛化性能较好。
        #--------------------------------------------------------------------------#
        "model_path"    : "model_data/facenet_mobilenet.h5",
        #--------------------------------------------------------------------------#
        #   输入图片的大小。
        #--------------------------------------------------------------------------#
        "input_shape"   : [160, 160, 3],
        #--------------------------------------------------------------------------#
        #   所使用到的主干特征提取网络
        #--------------------------------------------------------------------------#
        "backbone"      : "mobilenet"
    }

    @classmethod
    def get_defaults(cls, n):
        if n in cls._defaults:
            return cls._defaults[n]
        else:
            return "Unrecognized attribute name '" + n + "'"

    #---------------------------------------------------#
    #   初始化Facenet
    #---------------------------------------------------#
    def __init__(self, **kwargs):
        self.__dict__.update(self._defaults)
        for name, value in kwargs.items():
            setattr(self, name, value)
            
        self.generate()
        
    def generate(self):
        model_path = os.path.expanduser(self.model_path)
        assert model_path.endswith('.h5'), 'Keras model or weights must be a .h5 file.'
        #---------------------------------------------------#
        #   载入模型与权值
        #---------------------------------------------------#
        self.model = facenet(self.input_shape, backbone=self.backbone, mode="predict")
        self.model.load_weights(self.model_path, by_name=True)
        print('{} model loaded.'.format(model_path))
    
    def letterbox_image(self, image, size):
        if self.input_shape[-1] == 1:
            image = image.convert("RGB")
        iw, ih  = image.size
        w, h    = size
        scale   = min(w/iw, h/ih)
        nw      = int(iw*scale)
        nh      = int(ih*scale)

        image   = image.resize((nw,nh), Image.BICUBIC)
        new_image = Image.new('RGB', size, (128,128,128))
        new_image.paste(image, ((w-nw)//2, (h-nh)//2))
        if self.input_shape[-1] == 1:
            new_image = new_image.convert("L")
        return new_image

    #---------------------------------------------------#
    #   检测图片
    #---------------------------------------------------#
    def detect_image(self, image_1, image_2):
        #---------------------------------------------------#
        #   对输入图片进行不失真的resize
        #---------------------------------------------------#
        image_1 = self.letterbox_image(image_1, [self.input_shape[1], self.input_shape[0]])
        image_2 = self.letterbox_image(image_2, [self.input_shape[1], self.input_shape[0]])
        #---------------------------------------------------#
        #   进行图片的归一化
        #---------------------------------------------------#
        image_1 = np.asarray(image_1).astype(np.float64) / 255
        image_2 = np.asarray(image_2).astype(np.float64) / 255
        #---------------------------------------------------#
        #   添加上batch维度，才可以放入网络当中预测
        #---------------------------------------------------#
        photo1 = np.expand_dims(image_1, 0)
        photo2 = np.expand_dims(image_2, 0)
        #---------------------------------------------------#
        #   图片传入网络进行预测
        #---------------------------------------------------#
        output1 = self.model.predict(photo1)
        output2 = self.model.predict(photo2)
        #---------------------------------------------------#
        #   计算二者之间的距离
        #---------------------------------------------------#
        l1 = np.sqrt(np.sum(np.square(output1 - output2), axis=-1))

        # plt.subplot(1, 2, 1)
        # plt.imshow(np.array(image_1))

        # plt.subplot(1, 2, 2)
        # plt.imshow(np.array(image_2))
        # plt.text(-12, -12, 'Distance:%.3f' % l1, ha='center', va= 'bottom',fontsize=11)
        # plt.show()
        return l1
    # Save the weights using the `checkpoint_path` format
    # Include the epoch in the file name (uses `str.format`)
    checkpoint_path = "checkpoints/cp-{epoch:04d}.ckpt"
    checkpoint_dir = os.path.dirname(checkpoint_path)
    shutil.rmtree(checkpoint_dir)
    model.save_weights(checkpoint_path.format(epoch=0))

    # Save the entire model
    modelSavePath = 'saved_model'
    shutil.rmtree(modelSavePath)
    model.save('saved_model/FaceVerify')

**Comment by bubbliiiing** [comment]
You can load the save code in the generate method of the facenet class, you will not call it outside of the facenet class at all

**Comment by Primadual** [comment]
Just wanted to update you that I fixed the error when loading the saved model by turning off the model compilation when loading it via keras as follows: 

`model = tf.keras.models.load_model('saved_model/FaceVerify', compile=False)`

I trained the model myself using a small subset of CASIA-WebFace dataset (only 15,000 images). I was not happy with the results. So I trained it again on a medium size subset of dataset (this time 83,000 images). But the results have not significantly improved. In both cases I get training accuracy of 0.95 and validation accuracy of 0.85. So It works. But when I test it on my own dataset, the l1 distance values of the same person and different persons are very close (0.6 for same person, 0.8 for different people). While if I load the pre-trained model of Facenet I get better distinction (0.47 and 1.2). So do you think if I train on the whole CASIA-WebFace dataset (494414 images) I will be able to achieve similar results to the pre-trained model? 

BTW, here is the code I use for prediction from my own saved model:

`import tensorflow as tf
from PIL import Image
from tensorflow import keras
import numpy as np
from facenet import Facenet
from nets.facenet import facenet
from nets.facenet_training import FacenetDataset, LFWDataset, triplet_loss
import mtcnn
from numpy import expand_dims
from numpy import asarray
from mtcnn.mtcnn import MTCNN
from os import listdir
from matplotlib import pyplot

gpus = tf.config.experimental.list_physical_devices(device_type='GPU')
for gpu in gpus:
    tf.config.experimental.set_memory_growth(gpu, True)
    
model = tf.keras.models.load_model('saved_model/FaceVerify', compile=False)

#Check its architecture
model.summary()

# function for face detection with mtcnn
# extract a single face from a given photograph
def extract_face(filename, required_size=(160, 160)):
    # load image from file
    image = Image.open(filename)
    # convert to RGB, if needed
    image = image.convert('RGB')
    # convert to array
    pixels = asarray(image)
    # create the detector, using default weights
    detector = MTCNN()
    # detect faces in the image
    results = detector.detect_faces(pixels)
    # extract the bounding box from the first face
    x1, y1, width, height = results[0]['box']
    # bug fix
    x1, y1 = abs(x1), abs(y1)
    x2, y2 = x1 + width, y1 + height
    # extract the face
    face = pixels[y1:y2, x1:x2]
    # resize pixels to the model size
    image = Image.fromarray(face)
    image = image.resize(required_size)
    face_array = asarray(image)
    return face_array

# load the photo and extract the face
facePixels1 = extract_face('img/201908800240013996.bmp')
facePixels2 = extract_face('img/201908800240013994.bmp')

image_1 = facePixels1
image_2 = facePixels2

# Normalize the picture
image_1 = np.asarray(image_1).astype(np.float64) / 255
image_2 = np.asarray(image_2).astype(np.float64) / 255

# Add the batch dimension before it can be put into the network to predict
photo1 = np.expand_dims(image_1, 0)
photo2 = np.expand_dims(image_2, 0)

# The picture is transmitted to the network for prediction
output1 = model.predict(photo1)
output2 = model.predict(photo2)

output1String1 = output1[0]
output1String2 = output1[1]

output1Array1 = np.array(output1String1)
output1Array2 = np.array(output1String2)

output2Array1 = np.array(output2[0])
output2Array2 = np.array(output2[1])

# Calculate the distance between the two
l11 = np.sqrt(np.sum(np.square(output1Array2 - output2Array2), axis=-1))
print("probability only 128 vector = %5.3f" % l11)`

**Comment by bubbliiiing** [comment]
83000 pictures are not enough. Oh, hundreds of thousands of pictures are also small data sets. Under normal circumstances, there is still a big gap between the network effect after training with hundreds of thousands of pictures and that in the paper. It seems that more advanced face recognition networks such as arcface also need millions of data sets.

**Comment by Primadual** [comment]
So I trained on the whole Caisa web face dataset but the results did not improve! The pre-trained model is much better. Thanks for your help anyways.

**Comment by bubbliiiing** [comment]
Sorry, 3q, I am a little busy.
