### ISSUE TITLE
请问 这个可以用来训练其他的数据集吗？

### ISSUE THREAD

**Issue by alexHxun** [bubbliiiing/facenet-tf2#3]
可以直接用facedataset类来加载非人脸的数据集吗？

**Comment by bubbliiiing** [comment]
格式一样可以额

**Comment by alexHxun** [comment]
> 格式一样可以额

感谢，已解决，训练没有问题；

不过对于test部分，Lfw_pair.txt文件 不知道是什么意思。

个人对人脸识别领域不太了解，所以不太了解那个文件是啥意思。

anyway，感谢。

**Comment by bubbliiiing** [comment]
这里面就是人脸对呢

**Comment by alexHxun** [comment]
WARNING:tensorflow:multiprocessing can interact badly with TensorFlow, causing nondeterministic deadlocks. For high performance data pipelines tf.data is recommended.

用facenetdataset类，使用多线程的时候，出了这个警告，请问有什么办法吗，搜了半天没搜到具体的解决办法。
使用单一线程的时候没有这个警告。
看提示好像是推荐使用tf.data来构建数据管道

**Comment by alexHxun** [comment]
> 这里面就是人脸对呢



> 这里面就是人脸对呢

好的，了解了，Thanks
