### ISSUE TITLE
去掉softmax loss，效果很差，有什么建议吗？

### ISSUE THREAD

**Issue by alexHxun** [bubbliiiing/facenet-tf2#4]
只用triplets loss训练，效果很差，如果采样方式改为原论文中的semi-hard，会提升 很多吗？

对于使用triplets loss训练，有什么建议吗？
谢谢

**Comment by bubbliiiing** [comment]
改为原来的会有提升，但效果也一般吧，因为原文的数据集太大了

**Comment by alexHxun** [comment]
> 改为原来的会有提升，但效果也一般吧，因为原文的数据集太大了

好吧，谢谢
